### PR TITLE
brian python file

### PR DESCRIPTION
**Pull request by braynyte**

### CODE REVIEW

**Review by jmcamac — COMMENTED** [review]
Looks great! Minor ask. Can you add a section for autoformatting and add Black? https://black.readthedocs.io/en/stable/index.html

**Comment by braynyte** [comment]
Happy to.  How do I pull it back to make the changes?

**Comment by jmcamac** [comment]
I think you can make the changes locally, commit, and the push to the remote branch. The code in the pull request should change too. At least that's how it works in Gitlab.

**Comment by braynyte** [comment]
Sweet!  Done.

**Comment by jmcamac** [comment]
Ooh, I like the links! Can we use the markdown syntax for links? https://www.markdownguide.org/basic-syntax/#links

And could you add links for the rest? Just to be consistent.

**Review by jmcamac — APPROVED** [review]

**Pull request merged**
